/**
 * @file hotel5.cpp
 * @author Josef Polasek (josef.polasek@tuni.fi)
 * @date 27-09-2022
 * @brief Version for grade 5. What was added/changed:
 *          1. clear a console
 *          2. create a database of reservations (input + print)
 *          3. searching in reservations by 
 *              a) booking number
 *              b) name
 *          4. reservations generated by a computer (before user's input)
*/

/**** LIBRARIES ****/
#include <iostream>
#include <string>
#include <cstdlib>
#include <time.h>
using namespace std;

/**** CONSTANTS ****/
int HOTEL_SIZE;
int SINGLE_ROOM_PRICE = 100; 
int DOUBLE_ROOM_PRICE = 150; 

/**** GLOBAL VARIABLES ****/
int invoice = 0;
string name = "0"; 

/**** STRUCTURES ****/
struct room {
    int number;
    int price;
    bool free;
    bool double_room = false;
};

/**** FUNCTIONS ****/
/* checks whether the string is a number or not */
bool isNumber(string& str) {
    for (char const &c : str)
        if (std::isdigit(c) == 0) return false;
    return true;
}

/* clears console */
void clearConsole(int height = 60) {
    // temporary solution
    for (int i = 0; i < height; i++)
        cout << endl;
}

/* generates our hotel */
void generateHotel(room hotel[]) {
    /* initialize room numbers and price */
    srand(time(0));
    int status = 0;

    for(int i = HOTEL_SIZE/2; i < HOTEL_SIZE; i++)
        hotel[i].double_room = true;

    for (int i = 0; i < HOTEL_SIZE; i++) {
        hotel[i].number = i + 1;

        // price for each type
        if(hotel[i].double_room == false) hotel[i].price = SINGLE_ROOM_PRICE;
        else hotel[i].price = DOUBLE_ROOM_PRICE;
        
        // randomly book some rooms
        status = (rand() % 2);
        if (status == 1) hotel[i].free = false;
        else hotel[i].free = true;
    }
}

/* prints all information of all the rooms */
void printAllRooms (room hotel[]) {
    for (int i = 0; i < HOTEL_SIZE; i++) {

        cout << "Room number ";
        
        if (hotel[i].number < 10) cout << "0";
        cout << hotel[i].number << " " << endl;

        cout << "Status: ";
        if(hotel[i].free == true) cout << "free" << endl;
        else cout << "booked" << endl;

        cout << "Price: " << hotel[i].price << endl;
        cout << endl;
    }
}

/* prints room numbers of the free rooms */
void printFreeRooms (room hotel[]) {
    clearConsole();
    cout << "These rooms are free: " << endl;

    // single
    cout << "SINGLE: ";
    for (int i = 0; i < HOTEL_SIZE; i++) {
        if (!hotel[i].free || hotel[i].double_room == true) continue;
        
        if (hotel[i].number < 10) cout << "0";
        cout << hotel[i].number << " ";
    }
    cout << endl;

    // double
    cout << "DOUBLE: ";
    for (int i = 0; i < HOTEL_SIZE; i++) {
        if (!hotel[i].free || hotel[i].double_room == false) continue;
        
        if (hotel[i].number < 10) cout << "0";
        cout << hotel[i].number << " ";
    }

    cout << endl << endl;
}

/* shows available rooms */
int seeAvailableRooms (room hotel[]) {
    printFreeRooms(hotel);

    int action;
    
    cout << "Select action:" << endl;
    cout << "1. go back to main menu" << endl;
    cout << "2. see a database of reservations" << endl;
    cout << "3. make a reservation" << endl << endl;
    cout << "action: ";
    cin >> action;
    cout << endl; 

    return action;
}

/* shows available rooms */
int seeInvoice () {
    clearConsole();
    cout << "The invoice is: " << invoice << " euros. | PRICING: single room = " << SINGLE_ROOM_PRICE << " euros/night | " << 
            "double room = " << DOUBLE_ROOM_PRICE << " euros/night" << endl << endl;

    int action;
    
    cout << "Select action:" << endl;
    cout << "1. go back to main menu" << endl;
    cout << "2. see a database of reservations" << endl;
    cout << "3. make a reservation" << endl;
    cout << "4. finish booking" << endl << endl;
    cout << "action: ";
    cin >> action;
    cout << endl; 

    return action;
}

/* room reservation system */
void reserveRoom(room hotel[]) {
    int room, nights, action;
    
    if(name == "0") {
        clearConsole(60);
        cout << "Before we start, please tell us your name: ";
        getline(cin >> ws, name);
    }

    do {
        clearConsole();

        cout << "ROOM RESERVATION SYSTEM" << endl;
        printFreeRooms(hotel);
        cout << "Book a room: ";
        cin >> room;
        cout << endl;

        if(room < 1 || room > 50) cout << "This room doesn't exist! Please select a different number." << endl << endl;
        // else if (hotel[room-1].free == false) cout << "This room is booked. Pleaes select a different one." << endl << endl;
        else if (hotel[room-1].free == false) cout << "THIS ROOM IS BOOKED. PLEAES SELECT A DIFFERENT ONE." << endl << endl;
        else {
            hotel[room-1].free = false;
            cout << "Select the number of nights: ";
            cin >> nights;

            invoice += hotel[room-1].price * nights;
            cout << "Your invoice is: " << invoice << " euros." << endl;
            cout << endl;
        }

        cout << "Do you want to continue?" << endl;
        cout << "1. yes" << endl;
        cout << "0. no" << endl << endl;
        cout << "action: ";
        cin >> action;
        cout << endl;

    } while (action == 1);
    
}

/* finish booking and get a discount */
int finishBooking(room hotel[]) {
    clearConsole();

    // check if reservation was done
    if (name == "0" or invoice == 0) {
        cout << "You have to make a reservation first!" << endl << endl;
    } else {

        // get a random discount
        srand(time(0));
        int discount =  (rand() % 3) * 10;

        if (discount != 0) {
            cout << endl << "You are lucky today! We have a special discount for you! It's " << discount << " %." << endl << endl;
        }
        
        // get values
        bool original = true;
        int reservationNum;
        do
        {
            reservationNum = (rand() % 89999) + 10000;
            if (/* reservation number is in the list */false) original = false;
            else  original = true;
        } while (original == false);

        float final_price = invoice * (1-(discount/100.0));

        // output
        cout << "Reservation number: " << reservationNum << endl;
        cout << "Name: " << name << endl;
        cout << "Price: " << final_price << " euros." << endl << endl;

        // task 5

        // clear cache
        name = "0";
        invoice = 0;
        // ...
    }

    // select another action
    int action;
    cout << "Select action:" << endl;
    cout << "1. go back to main menu" << endl;
    cout << "2. see a database of reservations" << endl;
    cout << "3. make a reservation" << endl << endl;
    cout << "action: ";
    cin >> action;
    cout << endl; 

    return action;
}

/**** MAIN FUNCTION ****/
int main() {
    /* initialize hotel */
    srand(time(0));
    HOTEL_SIZE = ( (rand() % 20) + 20) * 2; //generates a random number in the range 40-80
    room hotel [HOTEL_SIZE];
    generateHotel(hotel);

    string input_option;
    int option;

    do
    {   
        clearConsole();

        /* console menu */
        cout << "HOTEL RESERVATION SYSTEM" << endl;
        cout << "1. book a room" << endl;
        cout << "2. see available rooms " << endl;
        cout << "3. see invoice " << endl;
        cout << "4. finish booking " << endl;
        cout << "0. exit programme" << endl << endl;
        cout << "Please select action: ";
        cin >> input_option;
        cout << endl;

        if (isNumber(input_option)) option = stoi(input_option);
        else option = -1;

        // for case 2
        int next = 0;

        /* by selected option starts a subroutine */
        switch (option)
        {
        case 0:
            // just break
            break;
        
        case 1:
            reserveRoom(hotel);
            break;

        case 2:
            next = seeAvailableRooms(hotel);
            break;

        case 3:
            next = seeInvoice();
            break;
        
        case 4:
            next = finishBooking(hotel);
            break;
        
        default:
            cout << "Error: incorrect input! Please try again." << endl << endl;
            break;
        }

        if (next == 2);
        else if(next == 3) reserveRoom(hotel);
        else if (next == 4) finishBooking(hotel);
        // reserveRoom(hotel);
    } while (option != 0);
        
    return 0;
}
